[WIP] Polygon and Circle Detection
Chameleon-Vision/chameleon-vision pull request #100
Opened 2020-06-03 20:16 UTC by XzibitGG

### Pipes

#### FindPolygonsPipe

- Input: List<Cont
- Ouput: List<CVShape>

#### FilterPolygonsPipe
- Takes in List<CVShape> and outputs filtered List<CVShape> based off perimeter, area, and desired shape

#### FindCirclesPipe
- Input: Pair<Mat, List<Contour>>
- Ouput: List<CVShape>

### Pipelines
- Fleshed out ColouredShapePipeline

### Testing
Not too much testing done yet. TODOs for testing include:
- [ ]  Use powercell images from WPI's ML dataset
- [ ] Use more FRC specific targets instead of perfect polygons

### Triangles
![image](https://user-images.githubusercontent.com/27208624/83684300-ccfc3b00-a5b4-11ea-92bf-9d961a53e1b5.png)

### Quadrilaterals 
![image](https://user-images.githubusercontent.com/27208624/83684312-d5ed0c80-a5b4-11ea-97d3-8bc221e4be94.png)

### Circles
![image](https://user-images.githubusercontent.com/27208624/83684629-5dd31680-a5b5-11ea-964d-97ed157ba4f2.png)

General Things left

- [ ] Test more
- [ ] Replace draw2dcontours pipe with draw2dshapes pipe
- [ ] Add solvepnp support
- [ ] Make HoughCircles params a part of FindCirclesPipe params

2020-06-06 22:17 UTC, Bankst requested changes
Get your `.gradle` folder in to `.gitignore`.
Make the file naming of your test images a common scheme

2020-06-06 22:17 UTC, Bankst commented on chameleon-server/src/main/java/com/chameleonvision/common/vision/pipeline/ColouredShapePipeline.java
> +
Just a nitpick. List the pipes in the order they used

2020-06-06 22:17 UTC, Bankst commented on chameleon-server/src/main/java/com/chameleonvision/common/vision/pipeline/ColouredShapePipeline.java
> +    protected void setPipeParams(
Same nitpick here. Set up the params in the pipe order.

2020-06-06 22:17 UTC, Bankst commented on chameleon-server/src/main/java/com/chameleonvision/common/vision/pipeline/ColouredShapePipeline.java
> +        List<CVShape> shapes;
Move this out of the loop and reuse it each time

2020-06-06 22:17 UTC, Bankst commented on chameleon-server/src/test/java/com/chameleonvision/common/vision/pipeline/ColouredShapePipelineTest.java
> +    public static void testTriangleDetection(
These methods don't need the `@Test` attribute if they don't assert anything.

2020-06-06 22:57 UTC, mcm001 commented
Can you uncommit the stuff in `.gradle`?

2020-06-16 03:35 UTC, Bankst approved these changes

2020-06-16 03:35 UTC, merged