Config
Chameleon-Vision/chameleon-vision pull request #101
Opened 2020-06-04 22:02 UTC by mcm001

2020-06-05 11:28 UTC, oriagranat9 submitted a review, later dismissed
looks good to me would also like @Bankst review before merging

2020-06-06 22:11 UTC, Bankst requested changes

2020-06-06 22:11 UTC, Bankst commented on chameleon-server/src/main/java/com/chameleonvision/common/configuration/CameraConfiguration.java
> +    public StreamDivisor divisor = StreamDivisor.NONE;
This needs to be removed.

2020-06-06 22:11 UTC, Bankst commented on chameleon-server/src/main/java/com/chameleonvision/common/configuration/NetworkConfig.java
> +    public String hostname = "Chameleon-vision";
lower-case the hostname

2020-06-06 22:11 UTC, Bankst commented on chameleon-server/src/main/java/com/chameleonvision/common/configuration/StreamDivisor.java
> +package com.chameleonvision.common.configuration;
This should be in the `common.vision` package, as it relates to the pipeline.

2020-06-07 19:25 UTC, merged